name: Update Image List
run-name: Updating image list because ${{ github.actor }} made a new commit
on: [push]
jobs:
  Update-Image-List:
    runs-on: ubuntu-latest
    steps:
      - name: write files in directory to .txt file
        uses: actions/checkout@v2
      - run: ls -Rpm1 ./images/gallery_images/ > images.txt # Saving file list into a file
      - name: save changes
        uses: actions-go/push@v1
        with:
          force: true
          commit-files: images.txt
          commit-message: Updating image list
